package com.thehiddenbrain.interop.patientaccess.conformance;

import org.springframework.stereotype.Component;
import org.springframework.web.util.HtmlUtils;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Self-contained HTML rendering of a run (no external assets, printable, shareable). */
@Component
public class HtmlReport {

    public String render(ConformanceRun run) {
        StringBuilder sb = new StringBuilder();
        sb.append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Conformance report ")
                .append(esc(run.id())).append("</title><style>")
                .append("body{font:14px/1.45 system-ui,sans-serif;color:#1f2937;margin:24px;max-width:1200px}h1{font-size:20px}h2{font-size:16px;margin-top:28px;border-bottom:1px solid #d1d5db;padding-bottom:4px}")
                .append("table{border-collapse:collapse;width:100%}th,td{text-align:left;vertical-align:top;padding:6px 8px;border-bottom:1px solid #e5e7eb;font-size:13px}")
                .append(".s{display:inline-block;padding:1px 8px;border-radius:999px;font-weight:600;font-size:12px}.PASS{background:#dcfce7;color:#166534}.FAIL{background:#fee2e2;color:#991b1b}")
                .append(".WARN{background:#fef3c7;color:#92400e}.INFO{background:#e0e7ff;color:#3730a3}.SKIP{background:#f3f4f6;color:#6b7280}.ERROR{background:#fecaca;color:#7f1d1d}")
                .append(".muted{color:#6b7280}.details{margin:4px 0 0;padding-left:18px;color:#374151}.summary span{margin-right:14px}code{font-size:12px}")
                .append("</style></head><body>");
        sb.append("<h1>Patient Access API conformance report</h1>");
        sb.append("<p><b>Environment:</b> ").append(esc(run.environmentName())).append(" &nbsp; <b>Patient:</b> ")
                .append(esc(run.patientId() == null ? "(none)" : run.patientId())).append(" &nbsp; <b>Run:</b> <code>").append(esc(run.id()))
                .append("</code> &nbsp; <b>Status:</b> ").append(esc(run.status())).append(" &nbsp; <b>Started:</b> ").append(run.startedAt())
                .append(run.finishedAt() == null ? "" : " &nbsp; <b>Finished:</b> " + run.finishedAt()).append("</p>");
        sb.append("<p class=\"summary\">");
        run.counts().forEach((k, v) -> sb.append("<span class=\"s ").append(k).append("\">").append(k).append(" ").append(v).append("</span>"));
        sb.append("</p>");
        if (run.error() != null) {
            sb.append("<p class=\"s ERROR\">").append(esc(run.error())).append("</p>");
        }
        Map<String, List<CheckResult>> byGroup = new LinkedHashMap<>();
        for (String g : ConformanceSuite.GROUPS.keySet()) {
            byGroup.put(g, new java.util.ArrayList<>());
        }
        for (CheckResult r : run.results()) {
            byGroup.computeIfAbsent(r.group(), k -> new java.util.ArrayList<>()).add(r);
        }
        for (Map.Entry<String, List<CheckResult>> e : byGroup.entrySet()) {
            if (e.getValue().isEmpty()) {
                continue;
            }
            String[] meta = ConformanceSuite.GROUPS.getOrDefault(e.getKey(), new String[]{e.getKey(), ""});
            sb.append("<h2>").append(esc(meta[0])).append("</h2><p class=\"muted\">").append(esc(meta[1])).append("</p>");
            sb.append("<table><thead><tr><th>Status</th><th>Check</th><th>Result</th><th>Severity</th><th>ms</th></tr></thead><tbody>");
            for (CheckResult r : e.getValue()) {
                sb.append("<tr><td><span class=\"s ").append(r.status()).append("\">").append(r.status()).append("</span></td>");
                sb.append("<td><b>").append(esc(r.title())).append("</b><br><code class=\"muted\">").append(esc(r.checkId())).append("</code></td>");
                sb.append("<td>").append(esc(r.message()));
                if (!r.details().isEmpty()) {
                    sb.append("<ul class=\"details\">");
                    for (String d : r.details()) {
                        sb.append("<li>").append(esc(d)).append("</li>");
                    }
                    sb.append("</ul>");
                }
                if (!r.requestIds().isEmpty()) {
                    sb.append("<div class=\"muted\">evidence: ").append(esc(String.join(", ", r.requestIds()))).append("</div>");
                }
                sb.append("</td><td>").append(r.severity()).append("</td><td>").append(r.durationMs()).append("</td></tr>");
            }
            sb.append("</tbody></table>");
        }
        sb.append("<p class=\"muted\">Generated by the Patient Access API Workbench. FAIL = a SHALL requirement is not met; WARN = a SHOULD; INFO = a MAY or an observation.</p>");
        sb.append("</body></html>");
        return sb.toString();
    }

    private static String esc(String s) {
        return s == null ? "" : HtmlUtils.htmlEscape(s);
    }
}
