-- Segmentation seed from League_Segmentation_Table_Design.xlsx (Loaded Rules / PostgreSQL Script tabs).
-- Rule changes in production go in as targeted UPDATE / INSERT scripts, never TRUNCATE.

INSERT INTO league_segmentation.segment_rule
  (segment_name, segment_category, league_capability, company, rule_group, evaluation_order, logical_operator, api_field, comparison_operator, rule_value, is_active)
VALUES
  -- onlineBillPay
  ('onlineBillPay', 'Premium payment', 'home', 'HPHC', 1, 1, 'AND', 'dependentType',         'EQUALS',     '01',          TRUE),
  ('onlineBillPay', 'Premium payment', 'home', 'HPHC', 1, 2, 'AND', 'memberCategory',        'EQUALS',     'B2I',         TRUE),
  ('onlineBillPay', 'Premium payment', 'home', 'HPHC', 1, 3, NULL,  'customerCategory',      'NOT_EQUALS', 'NH_39_WEEK',  TRUE),
  ('onlineBillPay', 'Premium payment', 'home', 'THP',  1, 1, 'AND', 'sourceSystemId',        'EQUALS',     '2001',        TRUE),
  ('onlineBillPay', 'Premium payment', 'home', 'THP',  1, 2, 'AND', 'planTypeCode',          'NOT_IN',     'SCO,PDP',     TRUE),
  ('onlineBillPay', 'Premium payment', 'home', 'THP',  1, 3, 'AND', 'coverageGroupTypeCode', 'EQUALS',     '2',           TRUE),
  ('onlineBillPay', 'Premium payment', 'home', 'THP',  1, 4, 'OR',  'hasActivePdp',          'IS_FALSE',   NULL,          TRUE),
  ('onlineBillPay', 'Premium payment', 'home', 'THP',  2, 5, 'AND', 'sourceSystemId',        'EQUALS',     '2001',        TRUE),
  ('onlineBillPay', 'Premium payment', 'home', 'THP',  2, 6, NULL,  'planTypeCode',          'EQUALS',     'CTH',         TRUE),
  -- optumRxCoverage
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'HPHC', 1, 1, NULL,  'basicMedicalDrugCoverageIndicator', 'IS_TRUE', NULL,        TRUE),
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'THP',  1, 1, 'AND', 'sourceSystemId',        'EQUALS',  '2001',      TRUE),
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'THP',  1, 2, 'AND', 'hasPharmacyRider',      'IS_TRUE', NULL,        TRUE),
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'THP',  1, 3, 'OR',  'product',               'NOT_IN',  'NPDP,RPDP', TRUE),
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'THP',  2, 4, 'AND', 'hasTmpMedicalCoverage', 'IS_TRUE', NULL,        TRUE),
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'THP',  2, 5, 'AND', 'hasActivePdp',          'IS_TRUE', NULL,        TRUE),
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'THP',  2, 6, 'OR',  'product',               'NOT_IN',  'NPDP,RPDP', TRUE),
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'THP',  3, 7, 'AND', 'sourceSystemId',        'EQUALS',  '2001',      TRUE),
  ('optumRxCoverage', 'Pharmacy', 'getcare', 'THP',  3, 8, NULL,  'product',               'EQUALS',  'PDP',       TRUE),
  -- allPublicPlansMa
  ('allPublicPlansMa', 'Plans', 'forms', 'THP', 1, 1, 'AND', 'sourceSystemId', 'EQUALS', '2026',   TRUE),
  ('allPublicPlansMa', 'Plans', 'forms', 'THP', 1, 2, NULL,  'subsidiary',     'EQUALS', 'THPPMA', TRUE),
  -- allTuftsMedicarePreferred
  ('allTuftsMedicarePreferred', 'Plans', 'forms', 'THP', 1, 1, 'AND', 'sourceSystemId', 'EQUALS',       '2001', TRUE),
  ('allTuftsMedicarePreferred', 'Plans', 'forms', 'THP', 1, 2, 'AND', 'planCode',       'CONTAINS',     'EG',   TRUE),
  ('allTuftsMedicarePreferred', 'Plans', 'forms', 'THP', 1, 3, NULL,  'planCode',       'NOT_CONTAINS', 'PDP',  TRUE),
  -- tmpOtcMa
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 1, 1,  'AND', 'sourceSystemId', 'EQUALS',   '2001',      TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 1, 2,  'AND', 'planTypeCode',   'EQUALS',   'SCO',       TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 1, 3,  'OR',  'coverageActive', 'IS_TRUE',  NULL,        TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 2, 4,  'AND', 'sourceSystemId', 'EQUALS',   '2001',      TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 2, 5,  'AND', 'planTypeCode',   'EQUALS',   'MAP',       TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 2, 6,  'OR',  'coverageActive', 'IS_TRUE',  NULL,        TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 3, 7,  'AND', 'sourceSystemId', 'EQUALS',   '2001',      TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 3, 8,  'AND', 'planCode',       'EQUALS',   'STD SAVER', TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 3, 9,  'OR',  'coverageActive', 'IS_TRUE',  NULL,        TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 4, 10, 'AND', 'sourceSystemId', 'EQUALS',   '2001',      TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 4, 11, 'AND', 'planCode',       'CONTAINS', 'SMV',       TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 4, 12, 'OR',  'coverageActive', 'IS_TRUE',  NULL,        TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 5, 13, 'AND', 'sourceSystemId', 'EQUALS',   '2064',      TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 5, 14, 'AND', 'product',        'EQUALS',   'DMA',       TRUE),
  ('tmpOtcMa', 'Spending Accounts', 'spendingaccounts', 'THP', 5, 15, NULL,  'coverageActive', 'IS_TRUE',  NULL,        TRUE),
  -- planOfCare
  ('planOfCare', 'Care Plans', 'documents', 'THP', 1, 1,  'AND', 'subsidiary',                 'EQUALS',  'THPPMA', TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 1, 2,  'AND', 'sourceSystemId',             'EQUALS',  '2026',   TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 1, 3,  'AND', 'product',                    'EQUALS',  'MC',     TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 1, 4,  'OR',  'planOfCareCoverageEligible', 'IS_TRUE', NULL,     TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 2, 5,  'AND', 'subsidiary',                 'EQUALS',  'THPPMA', TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 2, 6,  'AND', 'sourceSystemId',             'EQUALS',  '2026',   TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 2, 7,  'AND', 'product',                    'IN',      'PL,GT',  TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 2, 8,  'AND', 'planCode',                   'IN',      '10GT100000,10GT100001,10GT100002,10PL100001', TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 2, 9,  'OR',  'planOfCareCoverageEligible', 'IS_TRUE', NULL,     TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 3, 10, 'AND', 'subsidiary',                 'EQUALS',  'THPPMA', TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 3, 11, 'AND', 'sourceSystemId',             'EQUALS',  '2026',   TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 3, 12, 'AND', 'product',                    'IN',      'PL,GT',  TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 3, 13, 'AND', 'planCode',                   'IN',
     '10GT100004,10GT100005,10GT100006,10GT100007,10GT100008,10GT100009,10GT100010,10GT100011,10GT100012,10GT100013,10GT100014,10GT100015,10PL100002,10PL100003,10PL100004,10PL100005,10PL100006,10GT100016,10GT100017,10GT100018', TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 3, 14, 'OR',  'planOfCareCoverageEligible', 'IS_TRUE', NULL,     TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 4, 15, 'AND', 'subsidiary',                 'EQUALS',  'THPPMA', TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 4, 16, 'AND', 'sourceSystemId',             'EQUALS',  '2064',   TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 4, 17, 'AND', 'product',                    'EQUALS',  'DMA',    TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 4, 18, 'OR',  'planOfCareCoverageEligible', 'IS_TRUE', NULL,     TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 5, 19, 'AND', 'sourceSystemId',             'EQUALS',  '2001',   TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 5, 20, 'AND', 'planTypeCode',               'EQUALS',  'SCO',    TRUE),
  ('planOfCare', 'Care Plans', 'documents', 'THP', 5, 21, NULL,  'planOfCareCoverageEligible', 'IS_TRUE', NULL,     TRUE),
  -- interoperability
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 1, 1,  'AND', 'subsidiary',                       'EQUALS',  'THPPRI',     TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 1, 2,  'AND', 'sourceSystemId',                   'EQUALS',  '2048',       TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 1, 3,  'AND', 'coverageStarted',                  'IS_TRUE', NULL,         TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 1, 4,  'OR',  'groupProductEffectiveForCoverage', 'IS_TRUE', NULL,         TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 2, 5,  'AND', 'subsidiary',                       'EQUALS',  'THPPMA',     TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 2, 6,  'AND', 'sourceSystemId',                   'EQUALS',  '2026',       TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 2, 7,  'AND', 'product',                          'IN',      'PL,GT,MC',   TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 2, 8,  'AND', 'coverageStarted',                  'IS_TRUE', NULL,         TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 2, 9,  'OR',  'groupProductEffectiveForCoverage', 'IS_TRUE', NULL,         TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 3, 10, 'AND', 'sourceSystemId',                   'EQUALS',  '2064',       TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 3, 11, 'AND', 'product',                          'EQUALS',  'DMA',        TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 3, 12, 'OR',  'coverageActive',                   'IS_TRUE', NULL,         TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 4, 13, 'AND', 'sourceSystemId',                   'EQUALS',  '2001',       TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 4, 14, 'AND', 'planTypeCode',                     'IN',      'MR,SCO,MAP', TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 4, 15, 'AND', 'coverageStarted',                  'IS_TRUE', NULL,         TRUE),
  ('interoperability', 'Compliance / interoperability', 'settings', 'THP', 4, 16, NULL,  'groupProductEffectiveForCoverage', 'IS_TRUE', NULL,         TRUE);
